version: "3.8"

services:
  mysqldb:
    image: mysql
    container_name: mysqlBox
    restart: on-failure
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD : $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE : $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  box-app:
    depends_on:
      - mysqldb
    restart: unless-stopped
    image: dizizzz/box-service
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?serverTimezone=UTC",
      "spring.datasource.username" : "$MYSQLDB_USER",
      "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
      "spring.jpa.hibernate.ddl-auto" : "validate"
      }'
